{"uuid": "3b2eb4b2-580c-4bf3-9428-0c6b6e24f9f0", "children": ["692cb09e-cae9-4d29-a7ec-c42919b15f0e", "503cea39-55b5-4e6b-8010-e6a2cbdc2f7d"], "befores": [{"name": "_UnitTestCase__pytest_class_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device.\n\n", "trace": "  File \"c:\\myprograms\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\myprograms\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\myprograms\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"c:\\myprograms\\python\\lib\\site-packages\\_pytest\\unittest.py\", line 131, in fixture\n    setup()\n  File \"C:\\Users\\SunXueYu\\PycharmProjects\\Hmtt_Ui_Test\\case\\app\\test_query_article.py\", line 16, in setUpClass\n    cls.driver = DriverUtils.get_app_driver()\n  File \"C:\\Users\\SunXueYu\\PycharmProjects\\Hmtt_Ui_Test\\utils.py\", line 95, in get_app_driver\n    cls.__app_driver = appium.webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)\n  File \"c:\\myprograms\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 155, in __init__\n    proxy\n  File \"c:\\myprograms\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\myprograms\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"c:\\myprograms\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\myprograms\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1598577018455, "stop": 1598577061663}], "start": 1598577018455, "stop": 1598577061790}